### ISSUE TITLE
编译完成后缺少生成目录

### ISSUE THREAD

**Issue by he88** [jiayy2/audio_demos#2]
编译audio_demos功能包通过后，在运行阶段：
![image](https://github.com/jiayy2/audio_demos/assets/56917942/43221c8d-da29-4cc7-9ad6-98ee44489dff)
发现install/include目录下缺少audio_demos目录。这是当前docker中找到的所有audio_demos目录：
![截图 2023-11-30 10-34-15](https://github.com/jiayy2/audio_demos/assets/56917942/c5d577df-0558-4c22-b621-151dbb97b3c2)
为什么install/include目录下未出现audio_demos目录？如何解决？

**Comment by jiayy2** [comment]
当前的项目生成的是可执行程序，无需include目录，所以并未配置输出；
如需生成include目录，可在CMakeLists.txt文件中添加install配置：
参考：
install (
    DIRECTORY include/
    DESTINATION include/${PROJECT_NAME}
)

**Comment by jiayy2** [comment]
@he88 是否还有其他问题？

**Comment by he88** [comment]
将install/lib/audio_demos和install/share/audio_demos上传到机器狗的制定目录后，重启机器狗，发现功能包未找到：
![image](https://github.com/jiayy2/audio_demos/assets/56917942/d6670f03-a01f-4f32-98fc-7f6d5e1fdf96)

**Comment by jiayy2** [comment]
> 将install/lib/audio_demos和install/share/audio_demos上传到机器狗的制定目录后，重启机器狗，发现功能包未找到： ![image](https://private-user-images.githubusercontent.com/56917942/286922169-d6670f03-a01f-4f32-98fc-7f6d5e1fdf96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNTQxODEsIm5iZiI6MTcwMTM1Mzg4MSwicGF0aCI6Ii81NjkxNzk0Mi8yODY5MjIxNjktZDY2NzBmMDMtYTAxZi00ZjMyLTk4ZmMtN2Y2ZDVlMWZkZjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDE0MTgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZDdhMGYxMWVjN2RhYmE0ODU0Y2U4OTZiYzE3ZmY5MDAwZWEwMTZiNWMxMmUyNzcwMTZkNGI5NjhjNDBiMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kTaLJbUSnkam54pHX98Z2JPgtbM_Yyduwit-FTvEtXU)

ROS2的编译命令和安装路径问题引起.

一个简单方式可以如下:
1 在狗的/home/mi 目录下创建一个工作空间 mkdir -p cyberdog_ws/src
2 将源码拷贝到狗上,scp -r demo_audio mi@192.168.55.1:/home/mi/cyberdog_ws/src
3 编译 colcon build --merge-install --install-base /opt/ros2/cyberdog/ --packages-up-to audio_demos
4 source /opt/ros2/cyberdog/setup.bash
5 查看pkg是否能找到,ros2 pkg list | grep audio_demos 

稍后更新使用文档.

**Comment by he88** [comment]
前三步完成后，执行第四步的source命令会报错，提示找不到/opt/ros2/galactic/share/libg2o/local_setup.bash;
pkg能找到audio_demos，但是运行audio_demos功能包还是会出错：
![image](https://github.com/jiayy2/audio_demos/assets/56917942/165d8c52-5f92-4602-9870-a069712e9598)

**Comment by jiayy2** [comment]
> 前三步完成后，执行第四步的source命令会报错，提示找不到/opt/ros2/galactic/share/libg2o/local_setup.bash; pkg能找到audio_demos，但是运行audio_demos功能包还是会出错： ![image](https://private-user-images.githubusercontent.com/56917942/287152241-165d8c52-5f92-4602-9870-a069712e9598.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MTAwMzAsIm5iZiI6MTcwMTQwOTczMCwicGF0aCI6Ii81NjkxNzk0Mi8yODcxNTIyNDEtMTY1ZDhjNTItNWY5Mi00NjAyLTk4NzAtYTA2OTcxMmU5NTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA1NDg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwOGMyZjhiMjQ4NTYwZjFiOThiZTE2ZWVjMWEwMTRjODhjNTJmMjAyMDhhNGU2ZGEyOGRmODA0MGQxYzkyZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U5mj0M4LItoMrq6C5wK1D9GA24f5qPuHJLNe-_UfpLY)

名字写错了,talk  改为talker.
ros2 run audio_demos talker
可以用Tab自动补全功能查看ros pkg下面有什么.

**Comment by he88** [comment]
已成功运行功能包，感谢耐心解答问题。
